image: Visual Studio 2017 Preview

before_build:
  - nuget restore

build:
  project: NNG.NET.sln
  verbosity: minimal
  
# configuration for "master" branch
# build in Release mode and deploy to nuget
branches:
  only:
    - master
    - develop
    - /feature\/.*/
    - /bugfix\/.*/
    - /hotfix\/.*/
    - /release\/.*/

configuration: 
    - Release
    - Debug

platform:
    - x64

test:
# only assemblies to test
  assemblies:
    only:
      - '**\*Tests.dll'